pins:
  - pin: G7
    # H144_OUT_PWM1
    id: D13
    class: outputs
    function: Alternator Enable
    type: hs
    ts_name: C3-7 - Alternator Enable

  - pin: G16
    # H144_OUT_IO9
    id: G13
    class: outputs
    function: Coolant Pump
    type: hs
    ts_name: C3-16 - Coolant Pump

  - pin: G33
    function: CAN bus low
    type: can

  - pin: G49
    # H144_OUT_IO12
    id: A8
    class: outputs
    function: Radiator Fan Relay
    type: hs
    ts_name: C3-49 - Fan Relay

  - pin: G53
    function: CAN bus high
    type: can

  - pin: G55
    # H144_IN_CLT
    id: EFI_ADC_12
    type: av
    class: analog_inputs
    ts_name: C3-55 - CLT
    function: CLT
    color: purple

  - pin: G56
    # H144_IN_IAT
    id: EFI_ADC_13
    type: av
    class: analog_inputs
    ts_name: C3-56 - IAT
    function: IAT
    color: purple

  - pin: G57
    # H144_IN_AUX4
    id: EFI_ADC_7
    type: av
    class: analog_inputs
    ts_name: C3-57 - A/C Pressure
    function: A/C Pressure
    color: purple

  - pin: G58
    # H144_IN_MAP3
    id: EFI_ADC_2
    type: av
    class: analog_inputs
    ts_name: C3-58 - Baro
    function: Baro Pressure
    color: purple

  - pin: G59
    # H144_IN_MAP2
    id: EFI_ADC_11
    type: av
    class: analog_inputs
    ts_name: C3-59 - MAP
    function: MAP
    color: purple

  - pin: G66
    # H144_IN_VSS
    id: F11
    class: switch_inputs
    function: Vehicle Speed Sensor Input Pos
    type: hall
    ts_name: C3-66 - VSS Input
    color: gray

  - pin: G67
    function: Vehicle Speed Sensor Input Neg
    color: gray