pins:
  - pin: 26D
    function: Power GND
    type: gnd

info:
  title: AlphaX 8chan
  name: AlphaX 8chan
  image:
    file: 8chan-D.jpg
  pins:
    - pin: 1D
      x: 85
      y: 90
    - pin: 2D
      x: 110
      y: 90
    - pin: 3D
      x: 135
      y: 90
    - pin: 4D
      x: 160
      y: 90
    - pin: 5D
      x: 185
      y: 90
    - pin: 6D
      x: 205
      y: 90
    - pin: 7D
      x: 230
      y: 90
    - pin: 8D
      x: 100
      y: 120
    - pin: 9D
      x: 125
      y: 120
    - pin: 10D
      x: 145
      y: 120
    - pin: 11D
      x: 170
      y: 120
    - pin: 12D
      x: 195
      y: 120
    - pin: 13D
      x: 220
      y: 120
    - pin: 14D
      x: 100
      y: 150
    - pin: 15D
      x: 125
      y: 150
    - pin: 16D
      x: 145
      y: 150
    - pin: 17D
      x: 170
      y: 150
    - pin: 18D
      x: 195
      y: 150
    - pin: 19D
      x: 220
      y: 150
    - pin: 20D
      x: 85
      y: 180
    - pin: 21D
      x: 110
      y: 180
    - pin: 22D
      x: 135
      y: 180
    - pin: 23D
      x: 155
      y: 180
    - pin: 24D
      x: 180
      y: 180
    - pin: 25D
      x: 205
      y: 180
    - pin: 26D
      x: 230
      y: 180
