outputs:
  # TLE8888 injector channels
  GPIOE_14: "37 - Injector 1"
  GPIOE_13: "38 - Injector 2"
  GPIOE_12: "41 - Injector 3"
  GPIOE_11: "42 - Injector 4"
  # TC4427 ignition outputs (5v)
  GPIOD_4: "9 - Ignition 1"
  GPIOD_3: "10 - Ignition 2"
  GPIOD_2: "11 - Ignition 3"
  GPIOD_1: "12 - Ignition 4"
  # TC4427 general purpose output (selectable 5v/12v)
  GPIOD_7: "14 - GP Out 5"
  GPIOD_6: "13 - GP Out 6"

  # TLE8888 high current low side
  GPIOE_9:  "7 - Lowside 1"
  GPIOE_10: "3 - Lowside 2"

  # TLE8888 half bridges (pushpull, lowside, or high-low)
  GPIOE_8: "35 - GP Out 1"
  GPIOE_7: "34 - GP Out 2"
  TLE8888_PIN_20: "33 - GP Out 3"
  TLE8888_PIN_21: "43 - GP Out 4"

event_inputs:
  # RC filter input for hall
  GPIOA_5: "25 - Hall Cam"
  # TLE8888 VR/hall conditioner
  GPIOC_6: "45 - VR/Hall Crank"

switch_inputs:
  GPIOE_10: "Brake Switch"
  GPIOG_1: "Clutch Switch"

analog_inputs:
  EFI_ADC_0: "18 - AN temp 1"
  EFI_ADC_1: "23 - AN temp 2"
  EFI_ADC_2: "24 - AN temp 3"
  EFI_ADC_3: "22 - AN temp 4"
  EFI_ADC_4: "19 - AN volt 10"
  EFI_ADC_6: "32 - AN volt 2"
  EFI_ADC_7: "31 - AN volt 3"
  EFI_ADC_8: "36 - AN volt 8"
  EFI_ADC_9: "40 - AN volt 9"
  EFI_ADC_10: "27 - AN-VOLT-1"
  EFI_ADC_11: "Battery Sense"
  EFI_ADC_12: "19 - AN volt 4"
  EFI_ADC_13: "20 - AN volt 5"
  EFI_ADC_14: "32 - AN volt 6"
  EFI_ADC_15: "30 - AN volt 7"
