outputs:
  # TLE8888 injector channels
  GPIOE_14: "Injector #1"
  GPIOE_13: "Injector #2"
  GPIOE_12: "Injector #3"
  GPIOE_11: "Injector #4"
  # TC4427 ignition outputs (5v)
  GPIOD_4: "Ignition #1"
  GPIOD_3: "Ignition #2"
  GPIOD_2: "Ignition #3"
  GPIOD_1: "Ignition #4"
  # TC4427 general purpose output (selectable 5v/12v)
  GPIOD_7: "GP Out 5"
  GPIOD_6: "GP Out 6"

  # TLE8888 high current low side
  GPIOE_9:  "Lowside 1"
  GPIOE_10: "Lowside 2"

  # TLE8888 half bridges (pushpull, lowside, or high-low)
  GPIOE_8: "GP Out 1"
  GPIOE_7: "GP Out 2"
  TLE8888_PIN_20: "GP Out 3"
  TLE8888_PIN_21: "GP Out 4"

event_inputs:
  # RC filter input for hall
  GPIOA_5: "Hall Cam"
  # TLE8888 VR/hall conditioner
  GPIOC_6: "VR/Hall Crank"

switch_inputs:
  GPIOE_10: "Brake Switch"
  GPIOG_1: "Clutch Switch"

analog_inputs:
  EFI_ADC_0: "AN-TEMP-1"
  EFI_ADC_1: "AN-TEMP-2"
  EFI_ADC_2: "AN-TEMP-3"
  EFI_ADC_3: "AN-TEMP-4"
  EFI_ADC_4: "AN-VOLT-10"
  EFI_ADC_6: "AN-VOLT-2"
  EFI_ADC_7: "AN-VOLT-3"
  EFI_ADC_8: "AN-VOLT-8"
  EFI_ADC_9: "AN-VOLT-9"
  EFI_ADC_10: "AN-VOLT-1"
  EFI_ADC_11: "VBAT"
  EFI_ADC_12: "AN-VOLT-4"
  EFI_ADC_13: "AN-VOLT-5"
  EFI_ADC_14: "AN-VOLT-6"
  EFI_ADC_15: "AN-VOLT-7"
