#
# microRusEfi board
# https://github.com/rusefi/rusefi/wiki/Hardware_microRusEfi_wiring
#

outputs:
  # TLE8888 injector channels
  - id: TLE8888_PIN_1
    function: Injector 1
    ts_name: 37 - Injector 1
    type: inj

  - id: TLE8888_PIN_2
    function: Injector 2
    ts_name: 38 - Injector 1
    type: inj

  - id: TLE8888_PIN_3
    function: Injector 3
    ts_name: 41 - Injector 3
    type: inj

  - id: TLE8888_PIN_4
    function: Injector 4
    ts_name: 42 - Injector 4
    type: inj

  # TC4427 ignition outputs (5v)
  - id: GPIOD_4
    function: Ignition 1
    ts_name: 9 - Ignition 1
    type: ign

  - id: GPIOD_3
    function: Ignition 2
    ts_name: 10 - Ignition 2
    type: ign

  - id: GPIOD_2
    function: Ignition 3
    ts_name: 11 - Ignition 3
    type: ign

  - id: GPIOD_1
    function: Ignition 4
    ts_name: 12 - Ignition 4
    type: ign

  # TC4427 general purpose output (selectable 5v/12v)
  - id: GPIOD_7
    function: (see JP2 jumper note)
    ts_name: 14 - GP Out 5
    type: gp_high

  - id: GPIOD_6
    function: Alternator (see JP2 jumper note)
    ts_name: 13 - GP Out 6
    type: gp_high

  # default VVT TLE8888 high current low side: VVT1 TLE8888_OUT6
  - id: TLE8888_PIN_6
    function: VVT
    ts_name: 7 - Lowside 1
    type: ls

  # default Idle Air Control TLE8888 high current low side: VVT2 TLE8888_OUT5
  - id: TLE8888_PIN_5
    function: Idle solenoid
    ts_name: 3 - Lowside 2
    type: ls

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT21#91
  - id: TLE8888_PIN_21
    function: Fuel pump relay (IDLE stepper coil 1+)
    ts_name: 35 - GP Out 1
    type: [gp_low, gp_pp]
    
  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT22#89
  - id: TLE8888_PIN_22
    function: Fan relay (IDLE stepper coil 1-)
    ts_name: 34 - GP Out 2
    type: [gp_low, gp_pp]

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT23
  - id: TLE8888_PIN_23
    function: (IDLE stepper coil 2+)
    ts_name: 33 - GP Out 3
    type: [gp_low, gp_pp]

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT24
  - id: TLE8888_PIN_24
    function: (IDLE stepper coil 2+)
    ts_name: 43 - GP Out 4
    type: [gp_low, gp_pp]

  # J2
  - id: GPIOA_15
    ts_name: AUX J2 PA15

  - id: GPIOB_8
    ts_name: AUX J2 PB8

  - id: GPIOB_9
    ts_name:  AUX J2 PB9

  - id: GPIOC_12
    ts_name: AUX J2 PC12

  - id: GPIOE_0
    ts_name:  AUX J6 PE0

  - id: GPIOE_6
    ts_name:  AUX J10 PE6

  - id: GPIOE_5
    ts_name:  AUX J11 PE5

  - id: GPIOB_7
    ts_name: AUX J18 PB7

  - id: GPIOB_0
    ts_name: AUX AV8 reuse

  - id: GPIOB_1
    ts_name: AUX AV9 reuse

  - id: GPIOA_4
    ts_name: AUX AV10 reuse

  - id: GPIOC_4
    ts_name: AUX AV6 reuse


  # Dual purpose input/output
#  - id: TLE8888_PIN_12
#    ts_name: AV6 outmode

#  - id: TLE8888_PIN_11
#    ts_name: AV8 outmode

#  - id: TLE8888_PIN_10
#    ts_name: AV9 outmode

#  - id: TLE8888_PIN_13
#    ts_name: AV10 outmode




event_inputs:
  # RC filter input for hall
  - id: GPIOA_5
    ts_name: 25 - Hall Cam
    type: hall

  # TLE8888 VR/hall conditioner
  - id: GPIOC_6
    function: Crank VR+/hall
    ts_name: 45 - VR/Hall Crank
    type: vr hall

switch_inputs:
  - id: GPIOA_0
    function: CLT sensor
    ts_name: 18 - AN temp 1
    type: at

  - id: GPIOA_1
    function: IAT sensor
    ts_name: 23 - AN temp 2
    type: at

  - id: GPIOA_2
    ts_name: 24 - AN temp 3
    type: at

  - id: GPIOA_3
    ts_name: 22 - AN temp 4
    type: at

  - id: GPIOA_4
    ts_name: 28 - AN volt 10
    type: av

  # RC filter input for hall
  - id: GPIOA_5
    ts_name: 25 - Hall Cam
    type: hall

  - id: GPIOA_6
    ts_name: 26 - AN volt 2
    type: av

  - id: GPIOA_7
    function: Throttle Pedal Position Sensor (PPS)
    ts_name: 31 - AN volt 3
    type: av

  - id: GPIOB_0
    ts_name: 36 - AN volt 8
    type: av

  - id: GPIOB_1
    ts_name: 40 - AN volt 9
    type: av

  - id: GPIOC_0
    function: MAP sensor
    ts_name: 27 - AN volt 1
    type: av

  # GPIOC_1: Skipped - battery sense
  - id: GPIOC_2
    function: Starting from version 0.5.0 this pin can be used as 5V input for USB connection through main connector (No need to open case to access micro-USB connector)
    ts_name: 19 - AN volt 4
    type: av

  - id: GPIOC_3
    function: Throttle position sensor (TPS)
    ts_name: 20 - AN volt 5
    type: av

  - id: GPIOC_4
    function: External wideband O2 sensor
    ts_name: 32 - AN volt 6
    type: av

  - id: GPIOC_5
    ts_name: 30 - AN volt 7
    type: av

analog_inputs:
  # PA0 CLT
  - id: EFI_ADC_0
    function: CLT sensor
    ts_name: 18 - AN temp 1
    type: at
  
  # PA1 IAT
  - id: EFI_ADC_1
    function: IAT sensor
    ts_name: 23 - AN temp 2
    type: at
  
  # PA2
  - id: EFI_ADC_2
    ts_name: 24 - AN temp 3
    type: at

  # PA300
  - id: EFI_ADC_3
    ts_name: 22 - AN temp 4
    type: at

  # PA4 - also AUX REUSE
  - id: EFI_ADC_4
    ts_name: 28 - AN volt 10
    type: av

  # PA6 pull-down R31
  - id: EFI_ADC_6
    ts_name: 26 - AN volt 2
    type: av
  
  # PA7 - usually PPS Pedal Position Sensor
  - id: EFI_ADC_7
    function: Throttle Pedal Position Sensor (PPS)
    ts_name: 31 - AN volt 3
    type: av

  # PB0 - also AUX REUSE
  - id: EFI_ADC_8
    ts_name: 36 - AN volt 8
    type: av


  # PB1 - also AUX REUSE
  - id: EFI_ADC_9
    ts_name: 40 - AN volt 9
    type: av

  # PC0 MAP
  - id: EFI_ADC_10
    function: MAP Sensor
    ts_name: 27 - AN volt 1
    type: av

  # PC1
  - id: EFI_ADC_11
    ts_name: Battery Sense
    type: 12V

  # PC2 pull-down R131
  - id: EFI_ADC_12
    ts_name: 19 - AN volt 4
    type: av
  
  # PC3 TPS pull-down R41
  - id: EFI_ADC_13
    ts_name: 20 - AN volt 5
    type: av
  
  # PC4 - also AUX REUSE
  - id: EFI_ADC_14
    ts_name: 32 - AN volt 6
    type: av

  # PC5
  - id: EFI_ADC_15
    ts_name: 30 - AN volt 7
    type: av
