#
# microRusEfi board
# https://github.com/rusefi/rusefi/wiki/Hardware_microRusEfi_wiring
#

pins:
  - pin: 1
    id: EFI_ADC_11
    color: white right
    function: 12V Supply from main relay output, see also pin #29
    ts_name: Battery Sense
    type: 12V
    class: analog_inputs

  # default Idle Air Control TLE8888 high current low side: VVT2 TLE8888_OUT5
  - pin: 3
    id: TLE8888_PIN_5
    color: white
    function: Idle solenoid
    ts_name: 3 - Lowside 2
    type: ls
    class: outputs

  # default VVT TLE8888 high current low side: VVT1 TLE8888_OUT6
  - pin: 7
    id: TLE8888_PIN_6
    color: black
    function: VVT
    ts_name: 7 - Lowside 1
    type: ls
    class: outputs

  # TC4427 ignition outputs (5v)
  - pin: 9
    id: GPIOD_4
    color: dark blue
    function: Ignition 1
    ts_name: 9 - Ignition 1
    type: ign
    class: outputs

  - pin: 10
    id: GPIOD_3
    color: dark blue
    function: Ignition 2
    ts_name: 10 - Ignition 2
    type: ign
    class: outputs

  - pin: 11
    id: GPIOD_2
    color: dark blue
    function: Ignition 3
    ts_name: 11 - Ignition 3
    type: ign
    class: outputs

  - pin: 12
    id: GPIOD_1
    color: dark blue
    function: Ignition 4
    ts_name: 12 - Ignition 4
    type: ign
    class: outputs

  - pin: 13
    id: GPIOD_6
    color: yellow
    function: Alternator (see JP2 jumper note)
    ts_name: 13 - GP Out 6
    type: gp_high
    class: outputs

  # TC4427 general purpose output (selectable 5v/12v)
  - pin: 14
    id: GPIOD_7
    color: yellow
    function: (see JP2 jumper note)
    ts_name: 14 - GP Out 5
    type: gp_high
    class: output

  - pin: 18
    id: [GPIOA_0, EFI_ADC_0]
    color: red
    function: CLT sensor
    ts_name: 18 - AN temp 1
    type: at
    class: [switch_inputs, analog_inputs]

  - pin: 19
    id: [GPIOC_2, EFI_ADC_12]
    color: red
    function: Starting from version 0.5.0 this pin can be used as 5V input for USB connection through main connector (No need to open case to access micro-USB connector)
    ts_name: 19 - AN volt 4
    type: av
    class: [switch_inputs, analog_inputs]
  
  - pin: 20
    id: [GPIOC_3, EFI_ADC_13]
    color: red left
    function: Throttle position sensor (TPS)
    ts_name: 20 - AN volt 5
    type: av
    class: [switch_inputs, analog_inputs]

  - pin: 22
    id: [GPIOA_3, EFI_ADC_3]
    color: dark green
    ts_name: 22 - AN temp 4
    type: at
    class: [switch_inputs, analog_inputs]

  - pin: 23
    id: [GPIOA_1, EFI_ADC_1]
    color: dark green
    function: IAT sensor
    ts_name: 23 - AN temp 2
    type: at
    class: [switch_inputs, analog_inputs]

  - pin: 24
    id: [GPIOA_2, EFI_ADC_2]
    color: dark green
    ts_name: 24 - AN temp 3
    type: at
    class: [switch_inputs, analog_inputs]

  # RC filter input for hall
  - pin: 25
    id: GPIOA_5
    color: light blue right
    ts_name: 25 - Hall Cam
    type: hall
    class: [event_inputs, switch_inputs]
    
  - pin: 26
    id: [GPIOA_6, EFI_ADC_6]
    color: light blue
    ts_name: 26 - AN volt 2
    type: av
    class: [switch_inputs, analog_inputs]

  - pin: 27
    id: [GPIOC_0, EFI_ADC_10]
    color: light blue
    function: MAP sensor
    ts_name: 27 - AN volt 1
    type: av
    class: [switch_inputs, analog_inputs]

  - pin: 28
    id: [GPIOA_4, EFI_ADC_4]
    color: light blue left
    ts_name: 28 - AN volt 10
    type: av
    class: [switch_inputs, analog_inputs]

  - pin: 30
    id: [GPIOC_5, EFI_ADC_15]
    color: pink
    ts_name: 30 - AN volt 7
    type: av
    class: [switch_inputs, analog_inputs]

  - pin: 31
    id: [GPIOA_7, EFI_ADC_7]
    color: pink
    function: Throttle Pedal Position Sensor (PPS)
    ts_name: 31 - AN volt 3
    type: av
    class: [switch_inputs, analog_inputs]

  - pin: 32
    id: [GPIOC_4, EFI_ADC_14]
    color: pink
    function: External wideband O2 sensor
    ts_name: 32 - AN volt 6
    type: av
    class: [switch_inputs, analog_inputs]

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT23
  - pin: 33
    id: TLE8888_PIN_23
    color: orange right
    function: (IDLE stepper coil 2+)
    ts_name: 33 - GP Out 3
    type: [gp_low, gp_pp]
    class: outputs

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT22#89
  - pin: 34
    id: TLE8888_PIN_22
    color: orange
    function: Fan relay (IDLE stepper coil 1-)
    ts_name: 34 - GP Out 2
    type: [gp_low, gp_pp]
    class: outputs

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT21#91
  - pin: 35
    id: TLE8888_PIN_21
    color: orange 
    function: Fuel pump relay (IDLE stepper coil 1+)
    ts_name: 35 - GP Out 1
    type: [gp_low, gp_pp]
    class: outputs   

  - pin: 36
    id: [GPIOB_0, EFI_ADC_8]
    color: orange left    
    ts_name: 36 - AN volt 8
    type: av
    class: [switch_inputs, analog_inputs]

  - pin: 37
    id: TLE8888_PIN_1
    color: grey right
    function: Injector 1
    ts_name: 37 - Injector 1
    type: inj
    class: outputs

  - pin: 38
    id: TLE8888_PIN_2
    color: grey
    function: Injector 2
    ts_name: 38 - Injector 2
    type: inj
    class: outputs

  - pin: 40
    id: [GPIOB_1, EFI_ADC_9]
    color: grey
    ts_name: 40 - AN volt 9
    type: av
    class: [switch_inputs, analog_inputs]

  - pin: 41
    id: TLE8888_PIN_3
    color: brown right
    function: Injector 3
    ts_name: 41 - Injector 3
    type: inj
    class: outputs

  - pin: 42
    id: TLE8888_PIN_4
    color: brown
    function: Injector 4
    ts_name: 42 - Injector 4
    type: inj
    class: outputs

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT24
  - pin: 43
    id: TLE8888_PIN_24
    color: brown
    function: (IDLE stepper coil 2+)
    ts_name: 43 - GP Out 4
    type: [gp_low, gp_pp]
    class: outputs

  - pin: 45
    id: GPIOC_6
    color: light green right
    function: Crank VR+/hall
    ts_name: 45 - VR/Hall Crank
    type: vr hall
    class: event_inputs
