#
# VAZ 21126–1411020-40
#
#

pins:
  - pin: 101
# RZR wastegate
    function: 101 low side 1.5A output
    class: outputs
    type: ls
  - pin: 102
# RZR fuel pump driver PWM
    function: 102 low side 1.5A output
    class: outputs
    type: ls

  - pin: 103
    function: Analog GND
    type: GND
  - pin: 104
    function: Analog GND
    type: GND
  - pin: 105
    function: Analog GND
    type: GND
  - pin: 106
    function: Analog GND
    type: GND

  - pin: 107
    class: analog_inputs
# RZR start command
# VAZ mentions A/C pressure maybe switch? maybe AV?
# jumper
    ts_name: 107
    function: 107 TODO
  - pin: 108
# jumper
    function: Sometimes GND
    type: GND

  - pin: 109
# RZR Boost MAP
    class: analog_inputs
    function: Analog 109
  - pin: 110
# RZR Ambient Pressure
    class: analog_inputs
    function: 110 Analog Input

  - pin: 111
# jumper
# RZR & Polaris PPS2
    class: analog_inputs
    function: ___ PPS2
    ts_name: 111 Analog Input

  - pin: 112
# RZR Fuel Level
    class: analog_inputs
    function: 112 Analog Input
    ts_name: 112 Analog Input

  - pin: 113
    function: Brake Input
    ts_name: 113 Brake Input

  - pin: 114
# jumper
# I cannot find where have I seen 114 as PPS2?
    function: 114 Analog Input
    class: analog_inputs

  - pin: 115
    class: outputs
    ts_name: Main Relay
    function: Main Relay Control
    type: ls

  - pin: 116
    function: Ignition Switch KL15 / Battery Voltage Analog Input
    ts_name: 116 - Voltage From Key
    color: white

  - pin: 119
    class: analog_inputs
    function: ___ Analog Input

  - pin: 120
    function: 120 Switch

  - pin: 121
# jumper
# RZR Polaris VAZ PPS1
    function: ___ PPS1
    class: analog_inputs

  - pin: 123
    function: 123 Input

  - pin: 125
# jumper
    function: 125 Analog Supply

  - pin: 126
    # jumper
    function: 126 Analog Supply
    color: black

  - pin: 127
    function: K-Line

  - pin: 128
    function: Tach Output

  - pin: 129
    function: A29 output

  - pin: 131
# Polaris Radiator Relay
    function: 131 Relay Output
    class: outputs
    type: ls

  - pin: 132
    function: CAN bus high
    type: can

  - pin: 134
    function: 134 Switch
  - pin: 135
# VAZ brake pedal
    function: ___ Switch Input
  - pin: 136
# VAZ clutch pedal
    function: 136 Switch Input
  - pin: 137
    function: 137 Polaris

  - pin: 138
    # jumper
    function: 138 Analog Supply
    color: black

  - pin: 140
    class: outputs
    function: 140 relay output
    color: orange
    type: ls
  - pin: 141
    class: outputs
    function: Engine Radiator Fan
    color: orange
    type: ls
  - pin: 142
    class: outputs
    function: Fuel Pump Relay
    type: ls
  - pin: 144
    function: CAN bus low
    type: can
  - pin: 147
    function: 147 Switch
  - pin: 151
    class: outputs
    function: 151 relay output
  - pin: 152
    class: outputs
    function: 152 relay output
  - pin: 153
    function: Power GND
    type: GND
  - pin: 154
    function: Power GND
    type: GND
  - pin: 155
    function: +12V From Main Relay
  - pin: 156
    function: +12V From Main Relay

  - pin: 201
    # jumper
    function: Crank Sensor VR- Negative Input
    ts_name: 201 Crank VR-
  - pin: 202
    # via
    function: 203 Oxygen Sensor

  - pin: 203
    class: analog_inputs
    function: ___ TPS Throttle Position 1

  - pin: 204
    function: Analog GND
    type: GND

  - pin: 205
    function: Analog GND
    type: GND

  - pin: 206
    function: Analog GND
    type: GND
  - pin: 207
    function: Analog GND
    type: GND
# Polaris CLT GND
  - pin: 208
    function: Analog GND
    type: GND

  - pin: 210
    function: Pedal +5V Supply
  - pin: 213
    # jumper
    function: Crank Sensor VR+ Positive Input
    ts_name: 213 Crank VR+
  - pin: 215
    class: analog_inputs
    ts_name: 215 CLT
    function: CLT sensor
  - pin: 219
    class: analog_inputs
    ts_name: 219 MAP
    function: Manifold Pressure Sensor

  - pin: 220
    class: analog_inputs
    function: ___ TPS Throttle Position 2

  - pin: 223
# jumper
    function: ___ Analog Supply
    color: red

  - pin: 227
    ts_name: 227 IAT
    function: ___ Intake Air Temperature
  - pin: 231
    class: event_inputs
    ts_name: 231 Cam
    function: Cam Sensor
  - pin: 232
    class: event_inputs
    ts_name: 232 - VSS
    function: VSS in

  - pin: 233
# jumper
# 1KHz-12KHz
# 1k pull-up to 5v or 12v with hardware mod/jumper https://github.com/rusefi/hellen-112-17/issues/10
    function: MAF frequency

  - pin: 235
    function: 135 Low Side Output?
  - pin: 237
    # jumper
    function: Knock Signal
  - pin: 238
    # jumper
    function: Analog GND for Knock
    type: GND

  - pin: 242
    class: outputs
    type: ls
    function: injector output 2
  - pin: 243
    class: outputs
    type: ls
    function: injector output 3
  - pin: 244
    class: outputs
    type: ls
    function: injector output 1
  - pin: 245
    class: outputs
    type: ls
    function: injector output 4
  - pin: 246
    function: ___  low side 1.5A output
    type: ls
  - pin: 247
    function: Analog GND
    type: GND

  - pin: 250
    function: Power GND
    type: GND
  - pin: 251
    # jumper
    function: ETB positive DC Motor
    type: etb
    color: purple
  - pin: 252
    # jumper
    function: ETB negative DC Motor
    type: etb
    color: purple
  - pin: 253
    function: Coil 2
  - pin: 254
    function: Coil 3
  - pin: 255
    function: Coil 4
  - pin: 256
    function: Coil 1


info:
  cid: H-112
  title: H-112
  directory: hellen/hellen-112-17
  board_url: https://github.com/rusefi/rusefi/wiki/Hellen112-17
  name: H-112
  image:
    file: main.jpg
  pins:
    - pin: 101
      x: 117
      y: 345
    - pin: 102
      x: 153
      y: 345
    - pin: 103
      x: 195
      y: 345
    - pin: 104
      x: 225
      y: 345
    - pin: 105
      x: 260
      y: 345
    - pin: 106
      x: 295
      y: 345
    - pin: 107
      x: 324
      y: 345
    - pin: 108
      x: 360
      y: 345
    - pin: 109
      x: 394
      y: 345
    - pin: 110
      x: 428
      y: 345

    - pin: 112
      x: 500
      y: 345
    - pin: 113
      x: 130
      y: 280
    - pin: 114
      x: 160
      y: 280
    - pin: 115
      x: 195
      y: 280
    - pin: 116
      x: 230
      y: 280
    - pin: 117
      x: 261
      y: 280
    - pin: 118
      x: 295
      y: 280

    - pin: 120
      x: 365
      y: 280
    - pin: 121
      x: 400
      y: 280
    - pin: 122
      x: 429
      y: 280
    - pin: 123
      x: 465
      y: 280

    - pin: 125
      x: 116
      y: 251
    - pin: 126
      x: 152
      y: 251

    - pin: 130
      x: 290
      y: 251
    - pin: 131
      x: 325
      y: 251
    - pin: 132
      x: 365
      y: 251

    - pin: 134
      x: 429
      y: 251
    - pin: 135
      x: 462
      y: 251
    - pin: 136
      x: 497
      y: 251

    - pin: 138
      x: 152
      y: 184

    - pin: 140
      x: 225
      y: 184
    - pin: 141
      x: 265
      y: 184
    - pin: 142
      x: 300
      y: 184
    - pin: 144
      x: 360
      y: 184

    - pin: 153
      x: 335
      y: 125
    - pin: 154
      x: 385
      y: 125
    - pin: 155
      x: 435
      y: 125
    - pin: 156
      x: 485
      y: 125


    - pin: 201
      x: 675
      y: 350

    - pin: 203
      x: 750
      y: 350
    - pin: 204
      x: 775
      y: 350
    - pin: 205
      x: 820
      y: 350
    - pin: 206
      x: 854
      y: 350
    - pin: 207
      x: 889
      y: 350
    - pin: 208
      x: 928
      y: 350

    - pin: 210
      x: 975
      y: 350

    - pin: 213
      x: 675
      y: 285

    - pin: 215
      x: 745
      y: 285

    - pin: 219
      x: 875
      y: 285
    - pin: 220
      x: 910
      y: 285

    - pin: 223
      x: 1015
      y: 285

    - pin: 227
      x: 745
      y: 250

    - pin: 230
      x: 855
      y: 250
    - pin: 231
      x: 885
      y: 250
    - pin: 232
      x: 915
      y: 250
    - pin: 233
      x: 950
      y: 250

    - pin: 242
      x: 845
      y: 185
    - pin: 243
      x: 885
      y: 185
    - pin: 244
      x: 915
      y: 185
    - pin: 245
      x: 950
      y: 185
    - pin: 246
      x: 985
      y: 185
    - pin: 247
      x: 1015
      y: 185

    - pin: 250
      x: 745
      y: 125
    - pin: 251
      x: 800
      y: 125
    - pin: 252
      x: 845
      y: 125
    - pin: 253
      x: 900
      y: 125
    - pin: 254
      x: 945
      y: 125
    - pin: 255
      x: 1000
      y: 125
    - pin: 256
      x: 1045
      y: 125
