name: rusEFI console 11

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # todo: switch to 11 once we have modules access
      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Test Compiler
        run: javac -version

      - name: Build console
        working-directory: ./java_console
        run: ant
