name: rusEFI console

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Test Compiler
        run: javac -version

      - name: Install Tools
        run: sudo apt-get install sshpass

      - name: Generate Java (Antlr)
        working-directory: ./java_tools/configuration_definition
        run: ant antlr

      - name: Print GCC version
        working-directory: .
        run: gcc -v

      - name: Build Native Unit Tests as shared library
        working-directory: ./unit_tests/
        # we have a unit test of JNI thus we need to build shared library
        run: make -j4 SANITIZE=no build/lib_rusefi_test

      - name: Test console
        # at the moment 'jar' task does not depend on tests?! maybe because tests take some time?
        working-directory: ./java_console
        run: ant test

      - name: Build console
        working-directory: ./java_console
        run: ant server_jar

      - name: Attach console junit results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: console junit
          path: ./java_console/build/*.txt

      - name: Upload rusEFI server
        working-directory: .
        run: java_console/upload_file.sh ${{ secrets.RUSEFI_SSH_USER }} ${{ secrets.RUSEFI_SSH_PASS }} ${{ secrets.RUSEFI_SSH_SERVER }} build_server/autoupdate java_console_binary/rusefi_server.jar
