name: TS Plugin

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Test Compiler
        run: javac -version

      - name: Install Tools
        run: sudo apt-get install ncftp

      - name: Build TS plugin body
        working-directory: ./java_tools/ts_plugin
        run: ant

      - name: Upload plugin body
        working-directory: .
        run: java_console/upload_file.sh ${{ secrets.RUSEFI_BUILD_FTP_USER }} ${{ secrets.RUSEFI_BUILD_FTP_PASS }} ${{ secrets.RUSEFI_FTP_SERVER }} autoupdate java_tools/ts_plugin/build/jar/rusefi_plugin_body.jar

