name: TS Plugin

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Test Compiler
        run: javac -version

      - name: Install Tools
        run: |
          sudo bash misc/actions/add-ubuntu-latest-apt-mirrors.sh
          sudo apt-get install sshpass

      - name: Build TS plugin body
        working-directory: ./java_tools/
        run: ./gradlew :ts_plugin:shadowJar

      - name: Upload plugin body
        working-directory: .
        run: java_console/upload_file.sh ${{ secrets.RUSEFI_SSH_USER }} ${{ secrets.RUSEFI_SSH_PASS }} ${{ secrets.RUSEFI_SSH_SERVER }} build_server/autoupdate java_tools/ts_plugin/build/libs/rusefi_plugin_body.jar

