name: Unit Tests on Windows

on: [push,pull_request]

jobs:
  build:
    runs-on: windows-2019





    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - uses: actions/checkout@v4

    - name: Checkout Submodules
      run: |
        git submodule update --init --depth=1 unit_tests/googletest
        git submodule update --init --depth=1 firmware/libfirmware
        git submodule update --init --depth=1 firmware/ext/lua
        git submodule update --init --depth=1 firmware/controllers/lua/luaaa
        git submodule update --init --depth=1 firmware/controllers/can/wideband_firmware
        git submodule update --init --depth=1 java_console/peak-can-basic

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      # 8.1.0 from 2018 works!
      # available options see https://community.chocolatey.org/packages/mingw#versionhistory
      # 10.3.0 internal error in mingw32_gt_pch_use_address
      # 12 has pch https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105858
      # 13 has x86 issue https://github.com/egor-tensin/setup-mingw/issues/14
      with:
        version: 8.1.0




    - name: Print bash version
      working-directory: .
      run: bash --version

    - name: Test Java Compiler
      run: javac -version

    - name: Generate Configs, Enums & Live Documentation
      working-directory: ./firmware/
      run: bash gen_default_everything.sh

    - name: Print GCC version
      working-directory: .
      run: gcc -v

    - name: Print make version
      working-directory: .
      run: make -v

    - name: Compile
      working-directory: unit_tests
      run: make

    - name: Run Tests on Windows
      working-directory: unit_tests
      run: build/rusefi_test.exe
