name: Generate Interactive Pinouts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install prerequisite software
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        sudo apt-get update
        sudo apt-get install ncftp
        wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64
        chmod a+x yq_linux_amd64
        mkdir yqdir
        mv yq_linux_amd64 yqdir/yq
        echo "::add-path::`pwd`/yqdir/"

    - name: Set FTP variables
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        if [ "${{github.ref}}" = "refs/heads/master" ]; then
          echo "::set-env name=RUSEFI_FTP_SERVER::${{secrets.RUSEFI_FTP_SERVER}}";
          echo "::set-env name=RUSEFI_DOXYGEN_FTP_USER::${{secrets.RUSEFI_DOXYGEN_FTP_USER}}";
          echo "::set-env name=RUSEFI_DOXYGEN_FTP_PASS::${{secrets.RUSEFI_DOXYGEN_FTP_PASS}}";
        fi

    - name: Generate documentation
      run: bash ./misc/jenkins/generate_pinouts/gen_upload_pinouts.sh
