name: HW CI

on: [push, pull_request]

jobs:
  build-firmware:
    strategy:
      # Let all builds finish even if one fails early
      fail-fast: false
      matrix:
        build-target: [f407-discovery, proteus_f4]

        include:
          - build-target: f407-discovery
            script: hardware_ci_f4_discovery
            runs-on: hw-ci-f4-discovery
            folder: f407-discovery
            config-name: all
            ini-file: rusefi_f4-disco.ini

          - build-target: proteus_f4
            script: hardware_ci_proteus
            runs-on: hw-ci-proteus
            folder: proteus
            config-name: proteus_f4
            ini-file: rusefi_proteus_f4.ini

    runs-on: ${{matrix.runs-on}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Identify Agent
      run: uname -a

    - name: Generate Configs for HW CI
      working-directory: ./firmware/
      run: bash gen_config_default.sh

    - name: Generate Enum Strings
      working-directory: ./firmware/
      run: bash gen_enum_to_string.sh

    - name: Generate Board config
      working-directory: ./firmware/
      run: bash gen_config_board.sh ${{matrix.folder}} ${{matrix.config-name}}

    - name: Generate Live Documentation
      working-directory: ./firmware/
      run: bash gen_live_documentation.sh

    # Make sure the compiler works
    - name: Test Compiler
      run: arm-none-eabi-gcc -v

    # We aren't guaranteed a clean machine every time, so manually clean the output
    - name: Clean Build
      working-directory: ./firmware
      run: make clean

    - name: Set EXTRA env
      run: echo "EXTRA_2_PARAMS=-DHARDWARE_CI" >> $GITHUB_ENV

    - name: Check ModemManager
      run: systemctl status ModemManager.service
