name: Sync Wiki

on: gollum

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out docs repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: chuckwagoncomputing/rusefi_documentation

    - name: Merge
      run: |
        git remote add best-wiki-git https://github.com/rusefi/rusefi.wiki.git
        git fetch best-wiki-git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git merge best-wiki-git/master
	git push
